### ISSUE TITLE
Doesn't show textures for all blocks

### ISSUE THREAD

**Issue by lastuniverse** [PrismarineJS/prismarine-web-client#184] opened 2021-05-22 23:49 UTC
![image](https://user-images.githubusercontent.com/3473738/119243666-26180280-bb69-11eb-856f-c7d57067b040.png)

```
three.module.js:24647 Uncaught TypeError: material.onBuild is not a function
    at getProgram (three.module.js:24647)
    at setProgram (three.module.js:24809)
    at WebGLRenderer.renderBufferDirect (three.module.js:24010)
    at renderObject (three.module.js:24588)
    at renderObjects (three.module.js:24561)
    at WebGLRenderer.render (three.module.js:24341)
    at animate (index.js:253)
```

**Comment by AwesomestCode** [comment] 2021-05-23 01:11
Well, this is embarrassing. My guess is that this was caused by the latest THREE.js upgrade. I don't know if that was tested by a human.

**Comment by AwesomestCode** [comment] 2021-05-23 01:14
Issue confirmed (can reproduce). Will take a deeper look into this.

**Comment by ShrimpyStuff** [comment] 2021-06-02 14:08
This was closed in Awesomest's pr

**Comment by AwesomestCode** [comment] 2021-06-02 14:28
Closed by #185

**Closed by AwesomestCode** 2021-06-02 14:28 UTC
Labels: bug, reliability, urgent
