### ISSUE TITLE
How do i play singleplayer from the web client?

### ISSUE THREAD

**Issue by Adithr123** [PrismarineJS/prismarine-web-client#218] opened 2021-10-05 03:31 UTC

**Comment by rom1504** [comment] 2021-10-05 07:22
![image](https://user-images.githubusercontent.com/2346494/135978101-54dc81c7-656f-42c6-b164-aa0fd73be4df.png)
Press Play

**Comment by Adithr123** [comment] 2021-10-05 21:36
no, i mean singleplayer

**Comment by Adithr123** [comment] 2021-10-05 21:36
My mistake.

**Comment by Adithr123** [comment] 2021-10-05 21:41
ALso options button doesnt work on the server

**Comment by rom1504** [comment] 2021-11-12 21:11
duplicate of https://github.com/PrismarineJS/prismarine-web-client/issues/47

**Closed by rom1504** 2021-11-12 21:11 UTC
