### ISSUE TITLE
Can’t connect to flying-squid server

### ISSUE THREAD

**Issue by AndyGames531** [PrismarineJS/prismarine-web-client#299] opened 2022-05-05 02:59 UTC
first off, thank you to all the contributors for the prismarinejs project. Im not quite sure I understand correctly how the prismarinejs project works, but ill explain what ive done and you can correct me where im wrong and show me how to do it the right way. Im trying to create a mcserver accessible from a browser so Ive created a 1.16.1 minecraft server using the flying-squid project, ive hosted it on replit.com and tunneled it through ngrok to make it accessible from the internet (i used replit because my internet connection isnt good enough). I then used the live demo prismarine web client to try and connect to the server(if this changes anything, the server is set to online mode false). (dont mind the extensions, its a school computer)
![Screenshot 2022-05-04 10 53 11 PM](https://user-images.githubusercontent.com/82985435/166857350-ed4145f0-d5d7-43ce-ab3b-e206525e0f3e.png)
when I click connect, it loads and loads until i give up and come here for help
![Screenshot 2022-05-04 10 55 24 PM](https://user-images.githubusercontent.com/82985435/166857471-2d27a14e-22e3-419e-bf95-43b45d11b7ba.png)
I have a feeling it has something to do with the proxy. 
you guys are the experts, i need some help
please correct me if i am wrong on any of the information i have submitted and educate me on what i should do next time
thanks again, Andy

**Comment by AwesomestCode** [comment] 2022-05-05 03:04
Well, firstly you shouldn’t change the proxy’s port. That’s the port of the proxy, not the server.

However, other than that there’s a known incompatibility with flying-squid (ironic, I know, but that’s the case nonetheless): refer to issue #201, so no guarantees on if it works or not.

Could you please attach a console log? On a chromebook (which you seem to be on), you can access it by pressing Control-Shift-I. Copy and paste the contents there to here.

**Comment by AndyGames531** [comment] 2022-05-05 03:12
> Well, firstly you shouldn’t change the proxy’s port. That’s the port of the proxy, not the server.
> 
> However, other than that there’s a known incompatibility with flying-squid (ironic, I know, but that’s the case nonetheless): refer to issue #201, so no guarantees on if it works or not.
> 
> Could you please attach a console log? On a chromebook (which you seem to be on), you can access it by pressing Control-Shift-I. Copy and paste the contents there to here.

**Comment by AwesomestCode** [comment] 2022-05-05 03:23
Reopening per request on issue #300.

**Comment by AndyGames531** [comment] 2022-05-05 03:28
i have the replit console logs here

https://user-images.githubusercontent.com/82985435/166859566-0d85adfe-d240-4c2f-87f2-c0215855c52f.mp4

and the web client console logs here
![Screenshot 2022-05-04 11 12 10 PM](https://user-images.githubusercontent.com/82985435/166859750-ecde6137-0e79-438f-b64e-8285cba5f2b7.png)

**Comment by AwesomestCode** [comment] 2022-05-05 03:31
As I stated earlier, please don’t change the port of the proxy. Use the default of 443. It’s the port of the proxy, not your server, so setting it to 25565 basically tells the client to find a proxy on that port, which is nonexistent, so it complains that it can’t find the proxy.

**Comment by AndyGames531** [comment] 2022-05-05 03:35
thanks, I changed the ports
![Screenshot 2022-05-04 11 33 22 PM](https://user-images.githubusercontent.com/82985435/166860184-15690271-4336-4975-a323-78769b015da7.png)
 it shows its done
![Screenshot 2022-05-04 11 33 33 PM](https://user-images.githubusercontent.com/82985435/166860225-7da814a1-c11f-4f08-8ead-e5add739000c.png)
 and then gives me this error code
![Screenshot 2022-05-04 11 31 46 PM](https://user-images.githubusercontent.com/82985435/166860254-062e84c2-a21d-4100-af9d-1f0b852d3a32.png)
here are the logs
![Screenshot 2022-05-04 11 34 02 PM](https://user-images.githubusercontent.com/82985435/166860270-b0e8b15f-563f-4bdd-81f0-df0c5cd49cf9.png)

**Comment by AwesomestCode** [comment] 2022-05-05 03:38
This seems to be the exact same issue as #201 as it’s caused by an incompatibility with flying-squid. As there’s nothing we can do at the moment to fix this on your side (other than not using flying-squid), I’ll close this as a duplicate for now—feel free to follow that issue for further updates.

**Comment by AndyGames531** [comment] 2022-05-05 03:39
thats a bummer, thank you for the help

**Closed by AwesomestCode** 2022-05-05 03:38 UTC
