### ISSUE TITLE
Pause menu

### ISSUE THREAD

**Issue by AwesomestCode** [PrismarineJS/prismarine-web-client#176] opened 2021-04-03 22:50 UTC
(Equivalent to escape menu in normal MC)

**Comment by rom1504** [comment] 2021-04-04 00:05
duplicate of #67

**Comment by AwesomestCode** [comment] 2021-04-04 00:06
@rom1504 am confused: I thought that was for an options menu, not a pause menu

**Closed by rom1504** 2021-04-04 00:05 UTC

**Comment by rom1504** [comment] 2021-04-04 00:29
there is only one in game menu

**Comment by AwesomestCode** [comment] 2021-04-04 00:30
Don’t you have to click a button in the initial screen (where you select
singleplayer or multiplayer) for options in the Notchian client? Or am I
misremembering?

**Comment by rom1504** [comment] 2021-04-04 00:35
there are several options and screens in the in game menu yeah

**Comment by AwesomestCode** [comment] 2021-04-04 00:54
Are we just lumping them into a single issue?

**Comment by rom1504** [comment] 2021-04-04 01:16
feel free to define good sub parts and comment in the issue
