### ISSUE TITLE
It swears at the nodejs version, and this is in the browser. How so?

### ISSUE THREAD

**Issue by lastuniverse** [PrismarineJS/prismarine-web-client#356] opened 2023-12-24 21:52 UTC
![image](https://github.com/PrismarineJS/prismarine-web-client/assets/3473738/a91b98b9-10c1-4b13-aa8f-cfbacc712830)

**Comment by ZXMushroom63** [comment] 2023-12-25 09:05
I reckon it's this line of code:
https://github.com/PrismarineJS/prismarine-web-client/blob/master/index.js#L26

**Comment by zardoy** [comment] 2023-12-25 09:20
Duplicate of https://github.com/PrismarineJS/prismarine-web-client/issues/349 ?

**Comment by rom1504** [comment] 2023-12-25 10:53
Please fix

**Comment by lastuniverse** [comment] 2023-12-29 17:41
I can't fix it. I don't install this package locally. I just followed the link on the main page of the repository.

> Live demo at https://prismarinejs.github.io/prismarine-web-client/

**Comment by rom1504** [comment] 2023-12-29 18:17
Ok so someone else will need to fix it then

**Comment by ZXMushroom63** [comment] 2023-12-31 08:36
> Duplicate of #349 ?

Yep.

**Comment by zardoy** [comment] 2023-12-31 13:21
> > Duplicate of #349 ?
> 
> 
> 
> Yep.

Good! 👍

**Comment by rom1504** [comment] 2023-12-31 14:44
fixed

now need to fix https://github.com/PrismarineJS/prismarine-web-client/issues/357 to redeploy

**Comment by rom1504** [comment] 2023-12-31 16:56
fixed

**Closed by rom1504** 2023-12-31 16:56 UTC
